apiVersion: apps/v1
kind: Deployment
metadata:
  name: atomic-crm
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: atomic-crm
  template:
    metadata:
      labels:
        app: atomic-crm
    spec:
      containers:
      - name: atomic-crm
        image: atomic-crm:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: atomic-crm
  namespace: default
spec:
  selector:
    app: atomic-crm
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atomic-crm-ingress
  annotations:
    ngrok.ingress.kubernetes.io/scheme: https
spec:
  ingressClassName: ngrok
  rules:
    - host: mongrel-rapid-jointly.ngrok-free.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: atomic-crm
                port:
                  number: 80
